#!/usr/bin/env python
import sys

sys.path.append('/usr/share/pyshared')
sys.path.append('/usr/share/python-support/python-mapmerge')

from mapmerge import listen
from mapmerge.config import STOMP_HOSTNAME, STOMP_PORT

listen(STOMP_HOSTNAME, STOMP_PORT)
