#!/usr/bin/env python
import sys
import logging
import logging.handlers

sys.path.append('/usr/share/pyshared')
sys.path.append('/usr/share/python-support/python-mapmerge')

from mapmerge import listen
from mapmerge.config import STOMP_HOSTNAME, STOMP_PORT, LOGLEVEL, LOGHANDLER

root = logging.getLogger('')
root.setLevel(LOGLEVEL)
root.addHandler(LOGHANDLER)

logger = logging.getLogger(__name__)
logger.info('Start listening for messages')

listen(STOMP_HOSTNAME, STOMP_PORT)
