#!/usr/bin/env python
import sys
import logging

sys.path.append('/usr/share/pyshared')
sys.path.append('/usr/share/python-support/python-mapmerge')

from mapmerge import listen
from mapmerge.config import STOMP_HOSTNAME, STOMP_PORT, LOGLEVEL, LOGHANDLER

logger = logging.getLogger('mapmerge')
logger.setLevel(LOGLEVEL)
logger.addHandler(LOGHANDLER)

listen(STOMP_HOSTNAME, STOMP_PORT)
